sudo: required
services:
  - docker
before_install:
  - docker build -t chocomachine/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true chocomachine/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-498057972570"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: "AKIAXH5URRNNJLDRQD4Y"
    secret_access_key: "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"
